/**
 * Tangram puzzles — GENERATED by tools/compose-tangram.py. Do not edit.
 *
 * Each puzzle carries the solved placement of every piece. The target
 * silhouette is drawn by rendering these placements in shadow, so the
 * outline and the solution can never drift apart.
 *
 * Coordinates are in tangram units: the assembled classic square is 4x4.
 * `rot` is degrees clockwise, `flip` mirrors the piece (only the
 * parallelogram is chiral enough to need it).
 */

export const PIECE_SHAPES = {
  large: { count: 2, flippable: false, poly: [[-0.6667, -2.0000], [1.3333, 0.0000], [-0.6667, 2.0000]] },
  medium: { count: 1, flippable: false, poly: [[-1.3333, -0.6667], [0.6667, -0.6667], [0.6667, 1.3333]] },
  small: { count: 2, flippable: false, poly: [[-1.0000, -0.3333], [1.0000, -0.3333], [0.0000, 0.6667]] },
  square: { count: 1, flippable: false, poly: [[-1.0000, 0.0000], [0.0000, -1.0000], [1.0000, 0.0000], [0.0000, 1.0000]] },
  para: { count: 1, flippable: true, poly: [[-0.5000, 0.5000], [0.5000, 1.5000], [0.5000, -0.5000], [-0.5000, -1.5000]] },
};

export const PUZZLES = [
  {
    id: "diamond", name: "Diamond", tier: 1,
    solution: [
      { type: "small", x: 1.0000, y: 0.6667, rot: 180, flip: false },
      { type: "small", x: 1.0000, y: 1.3333, rot: 0, flip: false },
    ],
  },
  {
    id: "triangle", name: "Triangle", tier: 1,
    solution: [
      { type: "small", x: 1.0000, y: 0.3333, rot: 0, flip: false },
      { type: "small", x: 0.3333, y: 1.0000, rot: 270, flip: false },
    ],
  },
  {
    id: "bigsquare", name: "Big Square", tier: 1,
    solution: [
      { type: "medium", x: 0.6667, y: 0.6667, rot: 270, flip: false },
      { type: "small", x: 1.6667, y: 1.0000, rot: 90, flip: false },
      { type: "small", x: 1.0000, y: 1.6667, rot: 180, flip: false },
    ],
  },
  {
    id: "bigtri", name: "Big Triangle", tier: 2,
    solution: [
      { type: "large", x: 2.0000, y: 0.6667, rot: 90, flip: false },
      { type: "large", x: 0.6667, y: 2.0000, rot: 0, flip: false },
    ],
  },
  {
    id: "bowtie", name: "Bow Tie", tier: 2,
    solution: [
      { type: "large", x: 2.0000, y: 0.6667, rot: 90, flip: false },
      { type: "large", x: 2.0000, y: 3.3333, rot: 270, flip: false },
    ],
  },
  {
    id: "rect", name: "Long Brick", tier: 2,
    solution: [
      { type: "large", x: 2.0000, y: 0.6667, rot: 90, flip: false },
      { type: "medium", x: 0.6667, y: 1.3333, rot: 180, flip: false },
      { type: "small", x: 3.6667, y: 1.0000, rot: 90, flip: false },
      { type: "small", x: 3.0000, y: 1.6667, rot: 180, flip: false },
    ],
  },
  {
    id: "boat", name: "Sail Boat", tier: 2,
    solution: [
      { type: "medium", x: 0.6667, y: 4.6667, rot: 270, flip: false },
      { type: "large", x: 2.0000, y: 0.6667, rot: 90, flip: false },
      { type: "small", x: 1.0000, y: 2.3333, rot: 0, flip: false },
      { type: "small", x: 1.6667, y: 3.0000, rot: 90, flip: false },
    ],
  },
  {
    id: "house", name: "Little House", tier: 2,
    solution: [
      { type: "large", x: 2.0000, y: 2.6667, rot: 90, flip: false },
      { type: "large", x: 2.0000, y: 0.6667, rot: 90, flip: false },
      { type: "medium", x: 0.6667, y: 1.3333, rot: 180, flip: false },
      { type: "small", x: 3.6667, y: 1.0000, rot: 90, flip: false },
      { type: "small", x: 3.0000, y: 1.6667, rot: 180, flip: false },
    ],
  },
  {
    id: "classic", name: "The Square", tier: 3,
    solution: [
      { type: "large", x: 0.6667, y: 2.0000, rot: 0, flip: false },
      { type: "large", x: 2.0000, y: 3.3333, rot: 270, flip: false },
      { type: "small", x: 1.0000, y: 0.3333, rot: 0, flip: false },
      { type: "square", x: 2.0000, y: 1.0000, rot: 0, flip: false },
      { type: "medium", x: 3.3333, y: 0.6667, rot: 0, flip: false },
      { type: "small", x: 2.6667, y: 2.0000, rot: 90, flip: false },
      { type: "para", x: 3.5000, y: 2.5000, rot: 0, flip: false },
    ],
  },
  {
    id: "greattri", name: "Great Triangle", tier: 3,
    solution: [
      { type: "large", x: 2.0000, y: 0.6667, rot: 90, flip: false },
      { type: "large", x: 6.0000, y: 0.6667, rot: 90, flip: false },
      { type: "medium", x: 3.3333, y: 2.6667, rot: 0, flip: false },
      { type: "square", x: 4.0000, y: 1.0000, rot: 0, flip: false },
      { type: "small", x: 3.0000, y: 1.6667, rot: 180, flip: false },
      { type: "small", x: 5.3333, y: 2.0000, rot: 270, flip: false },
      { type: "para", x: 4.5000, y: 2.5000, rot: 0, flip: true },
    ],
  },
];

export const PUZZLE_COUNT = PUZZLES.length;
