/**
 * Tilt Maze — authored boards.
 *
 * GENERATED by tools/compose-mazes.py. Edit the spec there and re-run it
 * rather than nudging tiles here: that script is what proves every letter is
 * reachable in order, that the exit is reachable after the last of them, and
 * that no hole is sitting on the only route through.
 *
 * Top-down mazes, sized so the WHOLE board is on screen at once. No camera
 * scrolling: a child tilting a phone cannot also track a moving viewport, and
 * a maze you can only see part of is a memory test rather than a motor-skill
 * one.
 *
 * Legend
 *   #  wall          .  floor
 *   S  start         E  exit (opens once every letter is collected, in order)
 *   O  hole          ~  sticky mud (slows the ball)
 *   *  gem (optional bonus)
 *   x  decoy letter — a letter that is NOT in the word, and costs a heart
 *   1..9  letter slots — collected IN ORDER to spell the level's word
 *
 * Boards are 9 columns by 17 rows: a PORTRAIT shape, because the screen is
 * portrait. The previous near-square boards filled 90% of the width and 33%
 * of the height, leaving two thirds of the phone empty, and the tile had to
 * shrink to fit the width anyway.
 */


export const BOARDS = [
  {
    id: "t1", name: "First Steps", word: "cat", theme: "wood",
    teaches: "Tilt your phone to roll the ball",
    map: `
#########
#S#.....#
#.#.#.#.#
#.#...#2#
#.#.###.#
#.#..1#.#
#.###.#.#
#.....#.#
#######.#
#3......#
#.#######
#.......#
#######.#
#....x#.#
#.###.#.#
#.*.#.xE#
#########
`,
  },
  {
    id: "t2", name: "Mind the Holes", word: "sun", theme: "wood",
    teaches: "Holes swallow the ball — go around",
    map: `
#########
#S....xO#
#.#####.#
#.#*..O.#
#.#.#####
#.#..O..#
#.#####.#
#1..#.x.#
#.#.#.#x#
#.#.#.#.#
###.#.#.#
#..2#...#
#.#####.#
#...#...#
#.#.#.###
#3.....E#
#########
`,
  },
  {
    id: "t3", name: "The Long Way", word: "frog", theme: "stone",
    teaches: "Collect the letters in order",
    map: `
#########
#S....#.#
#####.#.#
#....1#.#
#.#####.#
#.#...xx#
#2#.#x#.#
#.#.#*#O#
#.#x#.#.#
#.#O#.#.#
#.###.#.#
#.3.#.#.#
###.#.#.#
#...#.#O#
#.###.#*#
#4.....E#
#########
`,
  },
  {
    id: "t4", name: "Sticky Business", word: "star", theme: "stone",
    teaches: "Mud slows you down",
    map: `
#########
#S#.....#
#.#x#x#.#
#...#*#~#
###1###.#
#....~#.#
#.###.#.#
#2..#...#
#.#.###.#
#.#~...x#
#.#######
#.3.#..O#
###.#.#.#
#.#.#*#.#
#~#.###x#
#~O4...E#
#########
`,
  },
  {
    id: "t5", name: "Spiral In", word: "ocean", theme: "ice",
    teaches: "Ice is slippery — tilt gently",
    map: `
#########
#S...1..#
#######.#
#.#...2.#
#*#.#####
#.#3....#
#.###.#4#
#...#x#.#
#.#.#.#.#
#O#.#.#.#
#x#O#O#.#
#*#...#5#
#.#####.#
#..x..x.#
#######.#
#...x..E#
#########
`,
  },
  {
    id: "t6", name: "The Gauntlet", word: "planet", theme: "ice",
    teaches: "Everything at once. Steady hands!",
    map: `
#########
#Sx~.~#O#
#.###x#O#
#...O.#*#
#.#####x#
#1#..x..#
#.###.#~#
#..2#.#.#
###.#.###
#.#.#.~.#
#O#.###x#
#x#3..#*#
#.###.#*#
#5...4#.#
#.#####.#
#..6...E#
#########
`,
  },
];
