/**
 * Tilt Maze — reading a board into something the game can play.
 *
 * Kept apart from `levels.js` because that file is GENERATED by
 * tools/compose-mazes.py, and regenerating it would otherwise take the parser
 * with it. The maps are data; this is the code that gives them meaning.
 */

import { BOARDS } from "./levels.js";

export const BOARD_COUNT = BOARDS.length;

/** Tile kinds after parsing. */
export const T = { FLOOR: 0, WALL: 1, HOLE: 2, MUD: 3, EXIT: 4 };

/**
 * Parse a board into a grid plus the objects on it.
 * Letters are returned in collection order, each carrying the letter of the
 * level's word it stands for.
 */
export function parseBoard(def) {
  const rows = def.map.replace(/^\n+|\n+$/g, "").split("\n");
  const h = rows.length;
  const w = Math.max(...rows.map((r) => r.length));
  const grid = Array.from({ length: h }, () => new Array(w).fill(T.WALL));
  const letters = [];
  const decoys = [];
  const gems = [];
  let start = { c: 1, r: 1 };
  let exit = { c: w - 2, r: h - 2 };

  for (let r = 0; r < h; r++) {
    for (let c = 0; c < w; c++) {
      const ch = rows[r][c] ?? "#";
      if (ch === "#") { grid[r][c] = T.WALL; continue; }
      grid[r][c] = T.FLOOR;
      if (ch === "O") grid[r][c] = T.HOLE;
      else if (ch === "~") grid[r][c] = T.MUD;
      else if (ch === "S") start = { c, r };
      else if (ch === "E") { exit = { c, r }; grid[r][c] = T.EXIT; }
      else if (ch === "*") gems.push({ c, r, taken: false });
      else if (ch === "x") decoys.push({ c, r, taken: false });
      else if (ch >= "1" && ch <= "9") letters.push({ order: +ch, c, r, taken: false });
    }
  }
  letters.sort((a, b) => a.order - b.order);
  // Map each slot to a letter of the word; extra slots wrap.
  const word = def.word.toUpperCase();
  letters.forEach((l, i) => { l.ch = word[i % word.length]; });

  // Decoys are letters that are NOT in the word, so a child has to read the
  // tray and pick rather than sweep up everything that glows. Chosen from the
  // cell's own coordinates rather than at random: a decoy that changes letter
  // between one attempt and the next teaches a child that reading is pointless.
  const pool = [..."ABCDEFGHIJKLMNOPRSTUW"].filter((ch) => !word.includes(ch));
  decoys.forEach((d, i) => { d.ch = pool[(d.c * 7 + d.r * 13 + i) % pool.length]; });

  return { ...def, grid, cols: w, rows: h, letters, decoys, gems, start, exit, word };
}

/**
 * Check a board is solvable: every letter, and the exit, reachable from the
 * start without crossing a wall. Holes are passable for this test because the
 * ball can be steered around them within a tile.
 */
export function auditBoard(b) {
  const issues = [];
  const seen = new Set();
  const key = (c, r) => r * b.cols + c;
  const q = [[b.start.c, b.start.r]];
  seen.add(key(b.start.c, b.start.r));
  while (q.length) {
    const [c, r] = q.shift();
    for (const [dc, dr] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
      const nc = c + dc, nr = r + dr;
      if (nc < 0 || nr < 0 || nc >= b.cols || nr >= b.rows) continue;
      if (b.grid[nr][nc] === T.WALL) continue;
      if (seen.has(key(nc, nr))) continue;
      seen.add(key(nc, nr));
      q.push([nc, nr]);
    }
  }
  for (const l of b.letters) {
    if (!seen.has(key(l.c, l.r))) issues.push(`letter ${l.order} at ${l.c},${l.r} is walled off`);
  }
  // A decoy nobody can reach is not a decoy, it is scenery — and it means the
  // generator walled off part of the board without anyone noticing.
  for (const d of b.decoys ?? []) {
    if (!seen.has(key(d.c, d.r))) issues.push(`decoy at ${d.c},${d.r} is walled off`);
  }
  if (!seen.has(key(b.exit.c, b.exit.r))) issues.push("exit is walled off");
  if (b.letters.length < 2) issues.push("needs at least two letters");
  return issues;
}
