/**
 * Huarong Dao layouts — GENERATED by tools/compose-slide.py. Do not edit.
 *
 * `par` is the true minimum number of single-cell slides, found by
 * breadth-first search over the whole state space, so the target shown
 * to the player is a fact rather than a guess.
 *
 * Board is 4 wide by 5 tall; the big block escapes through the gap in
 * the middle of the bottom edge.
 */

export const BOARD_W = 4;
export const BOARD_H = 5;
export const EXIT = { x: 1, y: 3 };

export const LAYOUTS = [
  {
    id: "s1", name: "First Slide", tier: 1, par: 2,
    blocks: [
      { id: "B", x: 1, y: 1, w: 2, h: 2 },
    ],
  },
  {
    id: "s2", name: "Two Guards", tier: 1, par: 4,
    blocks: [
      { id: "B", x: 2, y: 0, w: 2, h: 2 },
      { id: "G", x: 0, y: 0, w: 1, h: 1 },
      { id: "H", x: 0, y: 3, w: 1, h: 1 },
    ],
  },
  {
    id: "s3", name: "The Wall", tier: 2, par: 6,
    blocks: [
      { id: "B", x: 0, y: 0, w: 2, h: 2 },
      { id: "G", x: 3, y: 0, w: 1, h: 1 },
      { id: "H", x: 3, y: 1, w: 1, h: 1 },
      { id: "I", x: 0, y: 2, w: 1, h: 1 },
      { id: "J", x: 1, y: 2, w: 1, h: 1 },
      { id: "K", x: 3, y: 2, w: 1, h: 1 },
    ],
  },
  {
    id: "s4", name: "Narrow Pass", tier: 2, par: 13,
    blocks: [
      { id: "A", x: 0, y: 0, w: 1, h: 2 },
      { id: "B", x: 1, y: 0, w: 2, h: 2 },
      { id: "C", x: 3, y: 0, w: 1, h: 2 },
      { id: "D", x: 0, y: 2, w: 1, h: 2 },
      { id: "F", x: 3, y: 2, w: 1, h: 2 },
      { id: "G", x: 1, y: 3, w: 1, h: 1 },
      { id: "H", x: 2, y: 3, w: 1, h: 1 },
      { id: "I", x: 0, y: 4, w: 1, h: 1 },
      { id: "J", x: 3, y: 4, w: 1, h: 1 },
    ],
  },
  {
    id: "s5", name: "Four Generals", tier: 3, par: 23,
    blocks: [
      { id: "A", x: 0, y: 0, w: 1, h: 2 },
      { id: "B", x: 1, y: 0, w: 2, h: 2 },
      { id: "C", x: 3, y: 0, w: 1, h: 2 },
      { id: "D", x: 0, y: 2, w: 1, h: 2 },
      { id: "E", x: 1, y: 2, w: 2, h: 1 },
      { id: "F", x: 3, y: 2, w: 1, h: 2 },
      { id: "G", x: 0, y: 4, w: 1, h: 1 },
      { id: "H", x: 3, y: 4, w: 1, h: 1 },
    ],
  },
  {
    id: "s6", name: "Heng Dao Li Ma", tier: 3, par: 116,
    blocks: [
      { id: "A", x: 0, y: 0, w: 1, h: 2 },
      { id: "B", x: 1, y: 0, w: 2, h: 2 },
      { id: "C", x: 3, y: 0, w: 1, h: 2 },
      { id: "D", x: 0, y: 2, w: 1, h: 2 },
      { id: "E", x: 1, y: 2, w: 2, h: 1 },
      { id: "F", x: 3, y: 2, w: 1, h: 2 },
      { id: "G", x: 1, y: 3, w: 1, h: 1 },
      { id: "H", x: 2, y: 3, w: 1, h: 1 },
      { id: "I", x: 0, y: 4, w: 1, h: 1 },
      { id: "J", x: 3, y: 4, w: 1, h: 1 },
    ],
  },
];

export const LAYOUT_COUNT = LAYOUTS.length;
