import type { Rhyme } from '../engine/types';

/**
 * The rhyme corpus.
 *
 * Two halves, deliberately:
 *
 *  - `traditional` — lyrics published before 1928 and therefore public domain in
 *    the US. Parents want the classics and familiarity is a feature. Note that
 *    only the WORDS are free: specific recordings and arrangements carry their
 *    own copyright, so every one of these is spoken by the device's own voice
 *    and no existing arrangement is reproduced.
 *
 *  - `original` — written for this app, which makes them the ownable asset.
 *    They carry {child} and {companion} slots, tie to the eighteen worlds, and
 *    are built to the recipe in docs/RESEARCH-PLATFORM.md §5: trochaic metre,
 *    rhyme words at line end, a refrain to join, a dropped final word to supply,
 *    actions to tap the beat, and enough nonsense to be funny.
 */

const TRADITIONAL: Rhyme[] = [
  {
    id: 'twinkle',
    title: 'Twinkle, Twinkle, Little Star',
    kind: 'traditional',
    provenance: 'Words by Jane Taylor, 1806. Public domain.',
    worldId: 'starfall',
    emoji: '⭐',
    ageBands: ['3-5', '6-8'],
    devices: ['refrain', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: 'Twinkle, twinkle, little star,', rhyme: 'A', refrain: true, action: 'Open and close your hands like stars' },
      { text: 'How I wonder what you are.', cloze: 'are', rhyme: 'A', refrain: true },
      { text: 'Up above the world so high,', rhyme: 'B', action: 'Reach up high' },
      { text: 'Like a diamond in the sky.', cloze: 'sky', rhyme: 'B' },
      { text: 'Twinkle, twinkle, little star,', rhyme: 'A', refrain: true, action: 'Open and close your hands like stars' },
      { text: 'How I wonder what you are.', cloze: 'are', rhyme: 'A', refrain: true },
    ],
    rhymeGroups: [['star', 'are', 'car', 'far'], ['high', 'sky', 'fly', 'why']],
  },
  {
    id: 'hey-diddle',
    title: 'Hey Diddle Diddle',
    kind: 'traditional',
    provenance: 'Traditional, recorded by 1765. Public domain.',
    emoji: '🐄',
    ageBands: ['3-5', '6-8'],
    devices: ['nonsense', 'cloze'],
    meter: 'mixed',
    lines: [
      { text: 'Hey diddle diddle, the cat and the fiddle,', rhyme: 'A' },
      { text: 'The cow jumped over the moon.', cloze: 'moon', rhyme: 'B', action: 'Jump!' },
      { text: 'The little dog laughed to see such sport,', rhyme: 'C', action: 'Laugh out loud' },
      { text: 'And the dish ran away with the spoon.', cloze: 'spoon', rhyme: 'B', action: 'Run on the spot' },
    ],
    rhymeGroups: [['moon', 'spoon', 'soon', 'tune'], ['diddle', 'fiddle', 'middle']],
  },
  {
    id: 'hickory',
    title: 'Hickory Dickory Dock',
    kind: 'traditional',
    provenance: 'Traditional, recorded by 1744. Public domain.',
    emoji: '🕐',
    ageBands: ['3-5'],
    devices: ['refrain', 'cloze', 'actions', 'counting'],
    meter: 'trochaic',
    lines: [
      { text: 'Hickory dickory dock,', rhyme: 'A', refrain: true, action: 'Swing your arms like a pendulum' },
      { text: 'The mouse ran up the clock.', cloze: 'clock', rhyme: 'A', action: 'Run your fingers up your arm' },
      { text: 'The clock struck one,', rhyme: 'B', action: 'Hold up one finger' },
      { text: 'The mouse ran down,', rhyme: 'C', action: 'Run your fingers back down' },
      { text: 'Hickory dickory dock.', cloze: 'dock', rhyme: 'A', refrain: true },
    ],
    rhymeGroups: [['dock', 'clock', 'rock', 'sock'], ['one', 'run', 'sun', 'fun']],
  },
  {
    id: 'humpty',
    title: 'Humpty Dumpty',
    kind: 'traditional',
    provenance: 'Traditional, recorded by 1797. Public domain.',
    emoji: '🥚',
    ageBands: ['3-5', '6-8'],
    devices: ['cloze', 'actions'],
    meter: 'mixed',
    lines: [
      { text: 'Humpty Dumpty sat on a wall,', rhyme: 'A', action: 'Sit up tall' },
      { text: 'Humpty Dumpty had a great fall.', cloze: 'fall', rhyme: 'A', action: 'Flop over gently' },
      { text: 'All the king’s horses and all the king’s men', rhyme: 'B', action: 'Gallop on the spot' },
      { text: 'Couldn’t put Humpty together again.', cloze: 'again', rhyme: 'B' },
    ],
    rhymeGroups: [['wall', 'fall', 'tall', 'call'], ['men', 'again', 'ten', 'hen']],
  },
  {
    id: 'baa-baa',
    title: 'Baa, Baa, Black Sheep',
    kind: 'traditional',
    provenance: 'Traditional, recorded by 1744. Public domain.',
    worldId: 'bumblewick',
    emoji: '🐑',
    ageBands: ['3-5'],
    devices: ['call-response', 'cloze', 'counting'],
    meter: 'trochaic',
    lines: [
      { text: 'Baa, baa, black sheep, have you any wool?', voice: 'grownup', rhyme: 'A' },
      { text: 'Yes sir, yes sir, three bags full.', cloze: 'full', voice: 'companion', rhyme: 'A', action: 'Hold up three fingers' },
      { text: 'One for the master, one for the dame,', voice: 'companion', rhyme: 'C' },
      { text: 'And one for the little boy who lives down the lane.', cloze: 'lane', voice: 'companion', rhyme: 'B' },
    ],
    rhymeGroups: [['wool', 'full', 'pull'], ['lane', 'cane', 'plane', 'rain']],
  },
  {
    id: 'jack-jill',
    title: 'Jack and Jill',
    kind: 'traditional',
    provenance: 'Traditional, recorded by 1765. Public domain.',
    emoji: '🪣',
    ageBands: ['3-5', '6-8'],
    devices: ['cloze', 'actions'],
    meter: 'iambic',
    lines: [
      { text: 'Jack and Jill went up the hill', rhyme: 'A', action: 'Climb with your hands' },
      { text: 'To fetch a pail of water.', rhyme: 'B' },
      { text: 'Jack fell down and broke his crown,', rhyme: 'C', action: 'Tumble gently' },
      { text: 'And Jill came tumbling after.', cloze: 'after', rhyme: 'B' },
    ],
    rhymeGroups: [['hill', 'Jill', 'still', 'mill'], ['water', 'after']],
  },
  {
    id: 'mary-lamb',
    title: 'Mary Had a Little Lamb',
    kind: 'traditional',
    provenance: 'Words by Sarah Josepha Hale, 1830. Public domain.',
    worldId: 'bumblewick',
    emoji: '🐑',
    ageBands: ['3-5'],
    devices: ['refrain', 'cloze'],
    meter: 'trochaic',
    lines: [
      { text: 'Mary had a little lamb,', rhyme: 'A' },
      { text: 'Its fleece was white as snow.', cloze: 'snow', rhyme: 'B', action: 'Stroke your arm softly' },
      { text: 'And everywhere that Mary went,', rhyme: 'C' },
      { text: 'The lamb was sure to go.', cloze: 'go', rhyme: 'B', action: 'Walk on the spot' },
    ],
    rhymeGroups: [['snow', 'go', 'slow', 'know']],
  },
  {
    id: 'row-boat',
    title: 'Row, Row, Row Your Boat',
    kind: 'traditional',
    provenance: 'Traditional, published 1852. Public domain.',
    worldId: 'tidepool',
    emoji: '🚣',
    ageBands: ['3-5'],
    devices: ['refrain', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: 'Row, row, row your boat,', rhyme: 'A', refrain: true, action: 'Row with both arms' },
      { text: 'Gently down the stream.', cloze: 'stream', rhyme: 'B' },
      { text: 'Merrily, merrily, merrily, merrily,', rhyme: 'C', action: 'Row faster' },
      { text: 'Life is but a dream.', cloze: 'dream', rhyme: 'B', action: 'Rest your head on your hands' },
    ],
    rhymeGroups: [['stream', 'dream', 'cream', 'team'], ['boat', 'float', 'coat', 'goat']],
  },
  {
    id: 'miss-muffet',
    title: 'Little Miss Muffet',
    kind: 'traditional',
    provenance: 'Traditional, recorded by 1805. Public domain.',
    emoji: '🕷️',
    ageBands: ['3-5', '6-8'],
    devices: ['cloze', 'actions'],
    meter: 'mixed',
    lines: [
      { text: 'Little Miss Muffet sat on a tuffet,', rhyme: 'A', action: 'Sit down' },
      { text: 'Eating her curds and whey.', cloze: 'whey', rhyme: 'B', action: 'Pretend to eat' },
      { text: 'Along came a spider who sat down beside her,', rhyme: 'C', action: 'Walk your fingers like a spider' },
      { text: 'And frightened Miss Muffet away.', cloze: 'away', rhyme: 'B', action: 'Hop up!' },
    ],
    rhymeGroups: [['whey', 'away', 'day', 'play'], ['Muffet', 'tuffet']],
  },
  {
    id: 'star-light',
    title: 'Star Light, Star Bright',
    kind: 'traditional',
    provenance: 'Traditional American, 19th century. Public domain.',
    worldId: 'starfall',
    emoji: '✨',
    ageBands: ['3-5', '6-8'],
    devices: ['cloze'],
    meter: 'trochaic',
    lines: [
      { text: 'Star light, star bright,', rhyme: 'A', action: 'Point to the sky' },
      { text: 'First star I see tonight.', cloze: 'tonight', rhyme: 'A' },
      { text: 'I wish I may, I wish I might,', rhyme: 'A', action: 'Close your eyes' },
      { text: 'Have the wish I wish tonight.', cloze: 'tonight', rhyme: 'A' },
    ],
    rhymeGroups: [['light', 'bright', 'night', 'tonight', 'might', 'right']],
  },
];

const ORIGINAL: Rhyme[] = [
  {
    id: 'lumis-lanterns',
    title: "Lumi's Lanterns",
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    emoji: '🏮',
    ageBands: ['3-5', '6-8'],
    devices: ['refrain', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: 'Lumi has a lantern light,', rhyme: 'A', action: 'Hold both hands up like lanterns' },
      { text: 'Glowing gently, warm and bright.', cloze: 'bright', rhyme: 'A' },
      { text: 'One for morning, one for night,', rhyme: 'A', action: 'Show one hand, then the other' },
      { text: 'Hold them up and hold them tight!', cloze: 'tight', rhyme: 'A', action: 'Squeeze tight' },
      { text: 'Lumi, Lumi, lantern glow,', rhyme: 'B', refrain: true, action: 'Swing your lanterns side to side' },
      { text: 'Everywhere you go, we go!', cloze: 'go', rhyme: 'B', refrain: true },
    ],
    rhymeGroups: [
      ['light', 'bright', 'night', 'tight', 'right'],
      ['glow', 'go', 'slow', 'snow', 'know'],
    ],
  },
  {
    id: 'five-rockets',
    title: 'Five Small Rockets',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    worldId: 'starfall',
    emoji: '🚀',
    ageBands: ['3-5', '6-8'],
    devices: ['counting', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: 'One small rocket, painted red,', rhyme: 'A', action: 'Hold up one finger' },
      { text: 'Two soft pillows on the bed,', cloze: 'bed', rhyme: 'A', action: 'Hold up two' },
      { text: 'Three bright stars above the door,', rhyme: 'B', action: 'Hold up three' },
      { text: 'Four warm blankets on the floor,', cloze: 'floor', rhyme: 'B', action: 'Hold up four' },
      { text: 'Five brave astronauts in a row,', rhyme: 'C', action: 'Hold up five' },
      { text: 'Count them with me, nice and slow.', cloze: 'slow', rhyme: 'C', action: 'Count together, slowly' },
    ],
    rhymeGroups: [
      ['red', 'bed', 'head', 'said'],
      ['door', 'floor', 'four', 'more'],
      ['row', 'slow', 'go', 'glow'],
    ],
  },
  {
    id: 'companion-knows',
    title: 'Where Did You Go?',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    emoji: '🦊',
    ageBands: ['3-5', '6-8'],
    devices: ['call-response', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: '{companion}, {companion}, where did you go?', voice: 'grownup', rhyme: 'A', action: 'Cup your hand to your ear' },
      { text: 'Through the ferns and through the snow!', cloze: 'snow', voice: 'companion', rhyme: 'A', action: 'Tiptoe on the spot' },
      { text: '{companion}, {companion}, how do you know?', voice: 'grownup', rhyme: 'A', action: 'Shrug your shoulders' },
      { text: 'Follow me and I will show!', cloze: 'show', voice: 'companion', rhyme: 'A', action: 'Point the way' },
    ],
    rhymeGroups: [['go', 'snow', 'know', 'show', 'glow', 'slow']],
  },
  {
    id: 'quiet-dragon',
    title: 'The Very Quiet Dragon',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    worldId: 'quietdragon',
    emoji: '🐉',
    ageBands: ['3-5', '6-8', '9-11'],
    devices: ['cloze'],
    meter: 'trochaic',
    lines: [
      { text: 'Down below the winding stair', rhyme: 'A' },
      { text: 'Sleeps a dragon, old and kind.', rhyme: 'B' },
      { text: 'Every night he breathes out slow,', rhyme: 'C', action: 'Breathe out slowly' },
      { text: 'Warming all the ones behind.', cloze: 'behind', rhyme: 'B' },
      { text: 'He is not a scary sort,', rhyme: 'D' },
      { text: 'He is not a roaring one.', rhyme: 'E' },
      { text: 'All he guards is warm and small:', rhyme: 'F' },
      { text: 'Sleeping, till the night is done.', cloze: 'done', rhyme: 'E' },
    ],
    rhymeGroups: [
      ['kind', 'behind', 'find', 'mind'],
      ['one', 'done', 'sun', 'fun', 'run'],
    ],
  },
  {
    id: 'clap-cloudloom',
    title: 'Clap for the Cloudloom',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    worldId: 'cloudloom',
    emoji: '☁️',
    ageBands: ['3-5'],
    devices: ['actions', 'cloze'],
    meter: 'trochaic',
    lines: [
      { text: 'Clap your hands, the clouds are here!', rhyme: 'A', action: 'Clap three times' },
      { text: 'Stamp your feet, the rain is near!', cloze: 'near', rhyme: 'A', action: 'Stamp, stamp, stamp' },
      { text: 'Spin around and touch the ground,', rhyme: 'B', action: 'Spin, then touch the floor' },
      { text: 'Listen — hear that rumbling sound!', cloze: 'sound', rhyme: 'B', action: 'Freeze and listen' },
    ],
    rhymeGroups: [
      ['here', 'near', 'clear', 'cheer'],
      ['ground', 'sound', 'round', 'found'],
    ],
  },
  {
    id: 'lantern-deep',
    title: 'Down in Lantern Deep',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    worldId: 'lanterndeep',
    emoji: '🐋',
    ageBands: ['3-5', '6-8'],
    devices: ['cumulative', 'refrain', 'cloze'],
    meter: 'trochaic',
    lines: [
      { text: 'Down in Lantern Deep so blue,', rhyme: 'A', refrain: true, action: 'Wave your arms like water' },
      { text: 'Swam a turtle, old and true.', cloze: 'true', rhyme: 'A', action: 'Swim slowly' },
      { text: 'Then a jellyfish came too —', cloze: 'too', rhyme: 'A', action: 'Open and close your hands' },
      { text: 'Down in Lantern Deep so blue!', rhyme: 'A', refrain: true },
      { text: 'Turtle, jellyfish, and whale,', rhyme: 'B', action: 'Count them on your fingers' },
      { text: 'Singing one enormous tale.', cloze: 'tale', rhyme: 'B', action: 'Sing a long low note' },
    ],
    rhymeGroups: [
      ['blue', 'true', 'too', 'new', 'you'],
      ['whale', 'tale', 'sail', 'pale'],
    ],
  },
  {
    id: 'mittens',
    title: 'Mittens, Mittens',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    worldId: 'snowbell',
    emoji: '🧤',
    ageBands: ['3-5'],
    devices: ['counting', 'actions', 'cloze'],
    meter: 'trochaic',
    lines: [
      { text: 'Mittens, mittens, one and two,', rhyme: 'A', action: 'Hold up both hands' },
      { text: 'One for me and one for you!', cloze: 'you', rhyme: 'A', action: 'Point to yourself, then out' },
      { text: 'Boots and boots, three and four,', rhyme: 'B', action: 'Tap your feet' },
      { text: 'Stamp them loudly on the floor!', cloze: 'floor', rhyme: 'B', action: 'Stamp!' },
      { text: 'Scarves and scarves, five and six,', rhyme: 'C', action: 'Wind an imaginary scarf' },
      { text: 'Wind them round like candlesticks!', cloze: 'candlesticks', rhyme: 'C', action: 'Stand up tall and straight' },
    ],
    rhymeGroups: [
      ['two', 'you', 'blue', 'shoe'],
      ['four', 'floor', 'door', 'more'],
      ['six', 'candlesticks', 'sticks', 'bricks'],
    ],
  },
  {
    id: 'tock-robot',
    title: 'Tock the Little Robot',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    worldId: 'kindlymachine',
    emoji: '🤖',
    ageBands: ['3-5', '6-8'],
    devices: ['refrain', 'actions', 'cloze'],
    meter: 'trochaic',
    lines: [
      { text: 'Tick-tock, Tock the robot goes,', rhyme: 'A', refrain: true, action: 'March like a robot' },
      { text: 'Mending everything he knows.', cloze: 'knows', rhyme: 'A' },
      { text: 'Tighten, tighten, turn the screw,', rhyme: 'B', action: 'Twist your hand like a screwdriver' },
      { text: 'Now it works as good as new!', cloze: 'new', rhyme: 'B', action: 'Clap once' },
      { text: 'Tick-tock, Tock the robot goes,', rhyme: 'A', refrain: true, action: 'March like a robot' },
      { text: 'Off to bed on tiptoe toes.', cloze: 'toes', rhyme: 'A', action: 'Tiptoe quietly' },
    ],
    rhymeGroups: [
      ['goes', 'knows', 'toes', 'nose', 'rose'],
      ['screw', 'new', 'blue', 'two', 'you'],
    ],
  },
  {
    id: 'paper-crane',
    title: 'Paper Crane, Paper Crane',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    worldId: 'paperkingdom',
    emoji: '🕊️',
    ageBands: ['3-5', '6-8'],
    devices: ['call-response', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: 'Paper crane, oh paper crane,', voice: 'grownup', rhyme: 'A', action: 'Fold your hands together' },
      { text: 'Fold me up and fold again!', cloze: 'again', voice: 'companion', rhyme: 'A', action: 'Fold, fold, fold' },
      { text: 'Paper crane, where will you fly?', voice: 'grownup', rhyme: 'B', action: 'Shade your eyes and look up' },
      { text: 'Up above the paper sky!', cloze: 'sky', voice: 'companion', rhyme: 'B', action: 'Flap your arms' },
    ],
    rhymeGroups: [
      ['crane', 'again', 'rain', 'plane', 'train'],
      ['fly', 'sky', 'high', 'by', 'why'],
    ],
  },
  {
    id: 'silly-soup',
    title: 'Silly Soup',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    emoji: '🥣',
    ageBands: ['3-5', '6-8'],
    devices: ['nonsense', 'refrain', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: 'Put a fish into the soup,', rhyme: 'A', action: 'Drop it in' },
      { text: 'Put a purple hula hoop,', cloze: 'hoop', rhyme: 'A', action: 'Wiggle your hips' },
      { text: 'Put a boot and put a spoon,', rhyme: 'B', action: 'Drop them in' },
      { text: 'Stir it with a silver moon!', cloze: 'moon', rhyme: 'B', action: 'Stir the enormous pot' },
      { text: 'Silly soup, silly soup,', rhyme: 'A', refrain: true, action: 'Stir faster!' },
      { text: 'Everybody in the group!', cloze: 'group', rhyme: 'A', refrain: true, action: 'Everybody stir' },
    ],
    rhymeGroups: [
      ['soup', 'hoop', 'group', 'loop', 'scoop'],
      ['spoon', 'moon', 'soon', 'tune', 'balloon'],
    ],
  },
  {
    id: 'hop-like-lumi',
    title: 'Hop Like Lumi',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    emoji: '🦋',
    ageBands: ['3-5'],
    devices: ['actions', 'cloze', 'counting'],
    meter: 'trochaic',
    lines: [
      { text: 'Hop like Lumi, one, two, three,', rhyme: 'A', action: 'Hop three times' },
      { text: 'Flap your wings and fly with me!', cloze: 'me', rhyme: 'A', action: 'Flap your arms' },
      { text: 'Buzz around and touch the sky,', rhyme: 'B', action: 'Reach up as high as you can' },
      { text: 'Then come down and say goodbye!', cloze: 'goodbye', rhyme: 'B', action: 'Crouch down small and wave' },
    ],
    rhymeGroups: [
      ['three', 'me', 'see', 'tree', 'bee'],
      ['sky', 'goodbye', 'high', 'fly', 'why'],
    ],
  },
  {
    id: 'goodnight-everyone',
    title: 'Goodnight, Everyone',
    kind: 'original',
    provenance: 'Original, written for Lumi & the Sleepy Worlds.',
    emoji: '🌙',
    ageBands: ['3-5', '6-8'],
    devices: ['refrain', 'cloze', 'actions'],
    meter: 'trochaic',
    lines: [
      { text: 'Goodnight moon and goodnight mouse,', rhyme: 'A', action: 'Wave slowly' },
      { text: 'Goodnight every sleepy house.', cloze: 'house', rhyme: 'A', action: 'Make a roof with your hands' },
      { text: 'Goodnight {companion}, goodnight me,', rhyme: 'B', action: 'Hug yourself' },
      { text: 'Goodnight {child} — one, two, three.', cloze: 'three', rhyme: 'B', action: 'Close your eyes on three' },
    ],
    rhymeGroups: [
      ['mouse', 'house', 'blouse'],
      ['me', 'three', 'see', 'tree', 'bee'],
    ],
  },
];

export const RHYMES: Rhyme[] = [...ORIGINAL, ...TRADITIONAL];

export const RHYME_BY_ID = new Map(RHYMES.map((r) => [r.id, r]));

export function getRhyme(id: string): Rhyme {
  const rhyme = RHYME_BY_ID.get(id);
  if (!rhyme) throw new Error(`Unknown rhyme: ${id}`);
  return rhyme;
}
