/**
 * Assemble the shippable app into `www/`.
 *
 * There is no bundler here and that is deliberate. The whole codebase is
 * plain ES modules with zero runtime dependencies, so "building" is copying —
 * and a toolchain you do not have cannot rot, cannot break on a node upgrade,
 * and cannot silently change what ships versus what was tested. The files the
 * verification tools drive in a browser are byte-for-byte the files that go
 * into the store build.
 *
 * What this step does add:
 *   - it EXCLUDES parked work, so "not shipped" is structural rather than a
 *     note in a readme someone stops reading
 *   - it stamps a build id into the service worker, so a returning player
 *     actually gets the new version instead of a cached old one
 *   - it INJECTS the service-worker registration into the pages it emits,
 *     rather than the source doing it, so the development tree never fetches
 *     a generated file that is not there and never logs the 404 that would
 *     eventually hide a real error
 *
 *   node tools/build-app.mjs
 */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "www");

/** Shipped as-is. Anything not named here does not reach a store build. */
const INCLUDE = ["index.html", "manifest.webmanifest", "src"];

/**
 * Parked or development-only. Named explicitly rather than filtered by a
 * pattern, because a pattern quietly starts matching things later.
 */
const EXCLUDE = new Set([
  path.join("src", "games", "bloop.html"),
  path.join("src", "js", "games", "bloop"),
]);

const BUILD_ID = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);

function copy(rel) {
  if (EXCLUDE.has(rel)) return { files: 0, bytes: 0, skipped: 1 };
  const from = path.join(ROOT, rel);
  const to = path.join(OUT, rel);
  const stat = fs.statSync(from);
  if (stat.isDirectory()) {
    fs.mkdirSync(to, { recursive: true });
    let acc = { files: 0, bytes: 0, skipped: 0 };
    for (const name of fs.readdirSync(from)) {
      const r = copy(path.join(rel, name));
      acc.files += r.files; acc.bytes += r.bytes; acc.skipped += r.skipped;
    }
    return acc;
  }
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  return { files: 1, bytes: stat.size, skipped: 0 };
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

let files = 0, bytes = 0, skipped = 0;
for (const rel of INCLUDE) {
  const r = copy(rel);
  files += r.files; bytes += r.bytes; skipped += r.skipped;
}

// The offline shell. Everything is precached: the app has no network calls at
// all, so "offline" is simply how it always runs — on a plane, in a car, on a
// tablet that has never had a SIM.
const assets = [];
(function walk(dir) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) { walk(full); continue; }
    assets.push("/" + path.relative(OUT, full).split(path.sep).join("/"));
  }
})(OUT);

fs.writeFileSync(path.join(OUT, "sw.js"), `/* generated by tools/build-app.mjs */
const CACHE = "wordquest-${BUILD_ID}";
const ASSETS = ${JSON.stringify(assets.concat(["/"]), null, 0)};

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache first. There is no network to fall back to and nothing to freshen.
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request).catch(() => caches.match("/index.html")))
  );
});
`);

// Registration goes into the built pages only. Every page gets it, because a
// child can be dropped straight into a game by a home-screen shortcut without
// ever passing through the hub.
const REGISTER = `
<script>
if ("serviceWorker" in navigator && location.protocol !== "file:") {
  addEventListener("load", () => navigator.serviceWorker.register("/sw.js").catch(() => {}));
}
</script>
`;
let injected = 0;
(function inject(dir) {
  for (const name of fs.readdirSync(dir)) {
    const full = path.join(dir, name);
    if (fs.statSync(full).isDirectory()) { inject(full); continue; }
    if (!name.endsWith(".html")) continue;
    const html = fs.readFileSync(full, "utf8");
    if (!html.includes("</body>")) continue;
    fs.writeFileSync(full, html.replace("</body>", REGISTER + "</body>"));
    injected++;
  }
})(OUT);

console.log(`www/  ${files} files, ${(bytes / 1024).toFixed(0)} KB`);
console.log(`      offline registration injected into ${injected} page(s)`);
console.log(`      ${skipped} parked path(s) left out of the build`);
console.log(`      service worker precaches ${assets.length} assets as wordquest-${BUILD_ID}`);
